all:
	cd Smoothed\ Pseudo\ Wigner\ Ville\ Distribution; make rebuildRelease;
	cd Choi\ Williams\ Distribution; make rebuildRelease;
	cd Zaho\ Atlas\ Marks\ Distribution; make rebuildRelease;
	cd Pseudo\ Margenau\ Hill\ Distribution;make rebuildRelease;
	cd ../Short\ Time\ Fourier\ Transformation; make rebuild;

